### PR TITLE
修复低版本(UE5.6及之前)gameplaytag api问题

### PR DESCRIPTION
**Pull request by noobGuaTai**
使用UE 5.5.4编译报错：
`
[33/56] Compile [x64] UnrealBridgeGameplayTagLibrary.cpp
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(82): error C2039: "GameplayTagRedirects": 不是 "UGameplayTagsList" 的成员
D:\Code\UE_5.5\Engine\Source\Runtime\GameplayTags\Classes\GameplayTagsSettings.h(34): note: 参见“UGameplayTagsList”的声明
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(82): error C2530: “R”: 必须初始化引用
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(82): error C2143: 语法错误: 缺少“;”(在“:”的前面)
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(82): error C2143: 语法错误: 缺少“;”(在“)”的前面)
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(390): error C2660: “IGameplayTagsEditorModule::RenameTagInINI”: 函数不接受 3 个参数
D:\Code\UE_5.5\Engine\Plugins\Editor\GameplayTagsEditor\Source\GameplayTagsEditor\Public\GameplayTagsEditorModule.h(55): note: 参见“IGameplayTagsEditorModule::RenameTagInINI”的声明
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(390): note: 尝试匹配参数列表“(const FString, const FString, bool)”时
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(468): error C2039: "GameplayTagRedirects": 不是 "UGameplayTagsList" 的成员
D:\Code\UE_5.5\Engine\Source\Runtime\GameplayTags\Classes\GameplayTagsSettings.h(34): note: 参见“UGameplayTagsList”的声明
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(470): error C2039: "GameplayTagRedirects": 不是 "UGameplayTagsList" 的成员
D:\Code\UE_5.5\Engine\Source\Runtime\GameplayTags\Classes\GameplayTagsSettings.h(34): note: 参见“UGameplayTagsList”的声明
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(470): error C2530: “R”: 必须初始化引用
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(493): error C2039: "GameplayTagRedirects": 不是 "UGameplayTagsList" 的成员
D:\Code\UE_5.5\Engine\Source\Runtime\GameplayTags\Classes\GameplayTagsSettings.h(34): note: 参见“UGameplayTagsList”的声明
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(570): error C2039: "GameplayTagRedirects": 不是 "UGameplayTagsList" 的成员
D:\Code\UE_5.5\Engine\Source\Runtime\GameplayTags\Classes\GameplayTagsSettings.h(34): note: 参见“UGameplayTagsList”的声明
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(570): error C2530: “R”: 必须初始化引用
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(570): error C2143: 语法错误: 缺少“;”(在“:”的前面)
D:\Code\Programs\UE\ARPG 5.5\Plugins\UnrealBridge\Source\UnrealBridge\Private\UnrealBridgeGameplayTagLibrary.cpp(570): error C2143: 语法错误: 缺少“;”(在“)”的前面)
`

原因是

1. GameplayTagRedirects在5.5及之前的版本在UGameplayTagsSettings中声明，而5.6之后是在UGameplayTagsList声明
2. RenameTagInINI参数在5.5及之前只有两个

解决方法：

根据引擎版本不同调用不同的API

### CODE REVIEW

**Review by TornLux — COMMENTED** [review]
Thanks for the patch — the two underlying API shifts you identified are real (`FGameplayTagSource::SourceTagList` was added in 5.6, and `RenameTagInINI` grew the `bRenameChildren` parameter in a later 5.x). A few things to address before this can land, though:

### 1. Version-gate macro form

The repo standardises on `UE_VERSION_OLDER_THAN` from `Misc/EngineVersionComparison.h` (see `docs/version-compatibility.md` §"How the gate macro works"). The raw `ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 6` form here breaks on any future UE 6.x release, because for 6.0 `MINOR=0` is not `>= 6` and the old (wrong) branch will be taken. Please switch to:

```cpp
#include "Misc/EngineVersionComparison.h"

#if !UE_VERSION_OLDER_THAN(5, 6, 0)
    // new path (SourceTagList)
#else
    // legacy singleton path
#endif
```

…and the corresponding `!UE_VERSION_OLDER_THAN(5, 7, 0)` for the `RenameTagInINI` site (assuming 5.7 is the actual cutoff — see point 2).

### 2. Threshold for `RenameTagInINI` needs verifying

The PR uses `>= 5.6` for `SourceTagList` but `>= 5.7` for `RenameTagInINI`. If the 3-arg `RenameTagInINI(Old, New, bRenameChildren)` overload was actually introduced in 5.6, then a 5.6 build will still fail. Could you confirm against an installed 5.6 (or check `IGameplayTagsEditorModule.h` history)? If it's also 5.6, the gate should be `!UE_VERSION_OLDER_THAN(5, 6, 0)` for both sites.

### 3. Multi-source semantic loss in the legacy path (correctness bug)

On 5.5 and earlier, `UGameplayTagsSettings::GameplayTagRedirects` is a **single global list** with no per-source attribution — it aggregates redirects from every ini that contributes tags. The patch treats this singleton as if it were "the redirects of the current source", which causes two latent bugs in projects that have more than one tag source (e.g. `DefaultGameplayTags.ini` plus a `Config/Tags/*.ini` `TagList` source):

- **`EnsureSourceRedirectsPersisted(SourceName)`** iterates every entry in the singleton and re-appends any line missing from the source's ini. With this patch, a redirect declared in `DefaultGameplayTags.ini` will be re-written into the project-tag-list ini (and vice versa) the next time either source is touched, because the singleton can't tell them apart.
- **`RemoveGameplayTagRedirect`** sets `FoundSource` to whichever source the outer loop happened to be visiting when the matching pair was found in the singleton — then strips the line from `FoundSource->GetConfigFileName()`, which may be the wrong ini.

Two ways to fix:

(a) **Document the limitation explicitly** — in the legacy branch, early-return with a warning if more than one writable source exists, and note in the function comment that the legacy path only supports single-source projects.

(b) **Reconstruct per-source attribution from disk** — for each source's `GetConfigFileName()`, parse the actual `+GameplayTagRedirects=` lines out of that ini and use them as the per-source list, rather than trusting the in-memory singleton.

(a) is much smaller; (b) is the correct fix. Pick whichever you have time for, but please don't leave the silent corruption path in.

### 4. Build matrix coverage

The repo has `tools/build_matrix.py` that compiles the plugin against UE 5.4 and 5.7 to validate exactly this kind of cross-version gating (`docs/version-compatibility.md` §"Verifying"). Could you run it with whichever engines you have installed and paste the output? If you only have 5.5.4 locally, at minimum a 5.4 + 5.5 + 5.7 sweep would shake out the gate-threshold question in (2).

### 5. Documentation

After the gates are settled, please add a row to the "Inline shims" table in `docs/version-compatibility.md` for the GameplayTag library, noting which functions have a legacy code path and what the cutoff version is.

---

The intent and the diagnosis are exactly right; happy to land this once the gates are using the project macro and the legacy path either documents or fixes the multi-source case. Thanks!

**Comment by noobGuaTai** [comment]
Ok, I'll go make the changes.

**Comment by noobGuaTai** [comment]
# Changes are as follows：
# 1.Corrected the usage of engine version macros
# 2.Regarding the cutoff version for GameplayTag and RenameTagInINI, I have compiled the following documentation:
## 1. `GameplayTagRedirects` location change (5.5 → 5.6)

**File:** `Engine/Source/Runtime/GameplayTags/Classes/GameplayTagsSettings.h`

- [UE 5.5](https://github.com/EpicGames/UnrealEngine/blob/5.5/Engine/Source/Runtime/GameplayTags/Classes/GameplayTagsSettings.h)
- [UE 5.6](https://github.com/EpicGames/UnrealEngine/blob/5.6/Engine/Source/Runtime/GameplayTags/Classes/GameplayTagsSettings.h)
- [UE 5.7](https://github.com/EpicGames/UnrealEngine/blob/5.7/Engine/Source/Runtime/GameplayTags/Classes/GameplayTagsSettings.h)

### UE 5.5 — `GameplayTagRedirects` on `UGameplayTagsSettings` (child class only)

```cpp
// Base class — NO GameplayTagRedirects
class UGameplayTagsList : public UObject
{
    GENERATED_UCLASS_BODY()

    UPROPERTY()
    FString ConfigFileName;

    UPROPERTY(config, EditAnywhere, Category = GameplayTags)
    TArray<FGameplayTagTableRow> GameplayTagList;

    GAMEPLAYTAGS_API void SortTags();
};

// Child class — GameplayTagRedirects declared here
class UGameplayTagsSettings : public UGameplayTagsList
{
    GENERATED_UCLASS_BODY()
    // ...
    UPROPERTY(config, EditAnywhere, Category = GameplayTags, meta = (ConfigRestartRequired = true))
    TArray<FGameplayTagRedirect> GameplayTagRedirects;   // <-- ONLY on Settings
};
```

### UE 5.6+ — `GameplayTagRedirects` moved to `UGameplayTagsList` (base class)

```cpp
// Base class — now HAS GameplayTagRedirects
class UGameplayTagsList : public UObject
{
    GENERATED_UCLASS_BODY()

    UPROPERTY()
    FString ConfigFileName;

    UPROPERTY(config, EditAnywhere, Category = GameplayTags, meta = (ConfigRestartRequired = true))
    TArray<FGameplayTagRedirect> GameplayTagRedirects;   // <-- Moved to base class

    UPROPERTY(config, EditAnywhere, Category = GameplayTags)
    TArray<FGameplayTagTableRow> GameplayTagList;

    GAMEPLAYTAGS_API void SortTags();
};

// Child class — inherits from base, no longer declares it
class UGameplayTagsSettings : public UGameplayTagsList
{
    GENERATED_UCLASS_BODY()
    // ... GameplayTagRedirects no longer declared here
};
```

**Impact:** `Source->SourceTagList->GameplayTagRedirects` compiles on 5.6+ (where `SourceTagList` is `UGameplayTagsList*` and now has the member), but fails on 5.5 with `C2039: "GameplayTagRedirects" is not a member of "UGameplayTagsList"`.

---

## 2. `RenameTagInINI` parameter change (5.6 → 5.7)

**File:** `Engine/Plugins/Editor/GameplayTagsEditor/Source/GameplayTagsEditor/Public/GameplayTagsEditorModule.h`

- [UE 5.5](https://github.com/EpicGames/UnrealEngine/blob/5.5/Engine/Plugins/Editor/GameplayTagsEditor/Source/GameplayTagsEditor/Public/GameplayTagsEditorModule.h)
- [UE 5.6](https://github.com/EpicGames/UnrealEngine/blob/5.6/Engine/Plugins/Editor/GameplayTagsEditor/Source/GameplayTagsEditor/Public/GameplayTagsEditorModule.h)
- [UE 5.7](https://github.com/EpicGames/UnrealEngine/blob/5.7/Engine/Plugins/Editor/GameplayTagsEditor/Source/GameplayTagsEditor/Public/GameplayTagsEditorModule.h)

### UE 5.5 & 5.6 — 2 parameters

```cpp
GAMEPLAYTAGSEDITOR_API virtual bool RenameTagInINI(
    const FString& TagToRename,
    const FString& TagToRenameTo) = 0;
```

### UE 5.7+ — 3 parameters

```cpp
virtual bool RenameTagInINI(
    const FString& TagToRename,
    const FString& TagToRenameTo,
    bool bRenameChildren = true) = 0;
```

**Impact:** Calling `RenameTagInINI(Old, New, bRenameChildren)` on 5.5/5.6 fails with `C2660: function does not take 3 arguments`.

---

## 3. Multi-source limitation on 5.5

On 5.5 and earlier, `UGameplayTagsSettings::GameplayTagRedirects` is a **global singleton** that aggregates redirects from every ini file. There is no per-source attribution — it cannot distinguish between redirects from `DefaultGameplayTags.ini` and redirects from a `Config/Tags/*.ini` tag list source.

On 5.6+, `Source->SourceTagList->GameplayTagRedirects` provides **per-source** redirect lists, so each source's redirects are independent.

# 3.Following the Plan B you suggested, distinguish between different ini files to avoid conflicts.
# 4.I ran tools/build_matrix.py on UE 5.5.4, 5.6.1, and 5.7.4, and they all compiled successfully.

- Run: 2026-05-06T15:29:22
- Total duration: 4m 13s
- Config: `tools\engines.local.json`
- Plugin: `Plugin\UnrealBridge\UnrealBridge.uplugin`

## Summary

| Engine | Status | Duration | First Error |
|---|---|---|---|
| 5.5 | PASS | 1m 20s | — |
| 5.6 | PASS | 1m 33s | — |
| 5.7 | PASS | 1m 19s | — |

## Re-run

```
python tools/build_matrix.py                  # all enabled
python tools/build_matrix.py --only 5.7       # one version
python tools/build_matrix.py --verbose        # stream UAT output
```
